version: '3.6'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/
    ports:
      - '5432:5432'
    expose:
      - 5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 1s
      timeout: 1s
      retries: 20
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
        tmpfs:
          size: 104857600
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
